const MONTHS = ['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov'];

const SUMMARY = 'Your health score is currently showing some areas of concern. At this time, some of the tracked indicators are performing below optimal levels, and several biomarkers fall outside the recommended range. This suggests potential inconsistencies in your current health factors.';

export const METRICS = [
  {
    id: 1,
    slug: 'movement',
    title: 'Weekly activity balance',
    value: 85,
    label: 'Weekly activity score',
    score: 1,
    icon: 'movement',
    iconBg: '#09BC4E',
    chartType: 'line',
    chartData: [60, 62, 61, 65, 70, 72, 75, 78, 80, 85],
    detailStats: [
      { label: 'Active Minutes', value: '62', unit: 'min' },
      { label: 'Step Count', value: '8,543', unit: '' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [32, 34, 36, 39, 43, 41, 45, 47, 49],
      warning:  [11, 14, 17, 21, 24, 19, 18, 19, 15],
      critical: [4,  7,  9,  13, 17, 11, 8,  9,  6],
      optimalThreshold: 52,
      criticalThreshold: 78,
    },
    summary: SUMMARY,
    finalScore: 85,
    finalScoreSubtitle: 'Across 3 indicators',
    questionnaires: 6,
    questionnairesSubtitle: 'Optimal Reading',
    statusItems: [
      { title: 'Questionnaires', value: '6', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Biomarkers', value: '8', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Activity Score', value: '3', subtitle: 'Needs Attention', badge: 'Low', type: 'warning' },
    ],
  },
  {
    id: 2,
    slug: 'heart',
    title: 'Cardiovascular efficiency',
    value: 76,
    label: 'Cardiovascular score',
    score: 1,
    icon: 'heart-health',
    iconBg: '#E51C29',
    chartType: 'line',
    chartData: [70, 68, 72, 71, 74, 73, 75, 76, 74, 76],
    detailStats: [
      { label: 'Resting HR', value: '62', unit: 'bpm' },
      { label: 'Variability', value: '35', unit: 'ms' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [31, 33, 35, 38, 42, 40, 44, 45, 47],
      warning:  [12, 15, 18, 22, 25, 21, 18, 20, 16],
      critical: [5,  8,  10, 13, 17, 12, 8,  10, 7],
      optimalThreshold: 50,
      criticalThreshold: 76,
    },
    summary: SUMMARY,
    finalScore: 76,
    finalScoreSubtitle: 'Across 2 indicators',
    questionnaires: 8,
    questionnairesSubtitle: 'Optimal Reading',
    statusItems: [
      { title: 'Questionnaires', value: '3', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Biomarkers', value: '4.2', subtitle: 'Needs Immediate Attention', badge: 'Low', type: 'danger' },
      { title: 'Biomarkers', value: '8', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
    ],
  },
  {
    id: 3,
    slug: 'sleep',
    title: 'Recovery efficiency',
    value: 46,
    label: 'Recovery score',
    score: 1,
    icon: 'recovery',
    iconBg: '#3F54E4',
    chartType: 'line',
    chartData: [40, 42, 44, 41, 43, 45, 44, 46, 45, 46],
    detailStats: [
      { label: 'Sleep Quality', value: '72', unit: '%' },
      { label: 'HRV', value: '28', unit: 'ms' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [30, 32, 35, 38, 42, 40, 44, 46, 48],
      warning:  [12, 15, 18, 22, 25, 20, 18, 20, 16],
      critical: [5,  8,  10, 14, 18, 12, 8,  10, 6],
      optimalThreshold: 50,
      criticalThreshold: 75,
    },
    summary: SUMMARY,
    finalScore: 46,
    finalScoreSubtitle: 'Across 2 indicators',
    questionnaires: 4,
    questionnairesSubtitle: 'Below Average',
    statusItems: [
      { title: 'Questionnaires', value: '3', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Sleep Score', value: '4.2', subtitle: 'Needs Immediate Attention', badge: 'Low', type: 'danger' },
      { title: 'HRV', value: '2.8', subtitle: 'Needs Immediate Attention', badge: 'Low', type: 'danger' },
    ],
  },
  {
    id: 4,
    slug: 'brain',
    title: 'Mental clarity',
    value: 56,
    label: 'Mental clarity score',
    score: 1,
    icon: 'brain-health',
    iconBg: '#DE2ED7',
    chartType: 'bar',
    chartData: [30, 45, 50, 40, 55, 35, 56, 42, 38, 50],
    detailStats: [
      { label: 'Focus Score', value: '56', unit: '%' },
      { label: 'Stress Index', value: '42', unit: '' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [29, 32, 34, 37, 41, 39, 43, 45, 46],
      warning:  [12, 14, 17, 20, 24, 19, 17, 18, 15],
      critical: [6,  8,  10, 12, 16, 11, 9,  10, 7],
      optimalThreshold: 51,
      criticalThreshold: 77,
    },
    summary: SUMMARY,
    finalScore: 56,
    finalScoreSubtitle: 'Across 2 indicators',
    questionnaires: 5,
    questionnairesSubtitle: 'Average Reading',
    statusItems: [
      { title: 'Questionnaires', value: '5', subtitle: 'Average Reading', badge: 'In Range', type: 'success' },
      { title: 'Stress Level', value: '7', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Focus', value: '3', subtitle: 'Needs Immediate Attention', badge: 'Low', type: 'danger' },
    ],
  },
  {
    id: 5,
    slug: 'emotional',
    title: 'Emotional Health + Stress',
    value: 81,
    label: 'Emotional health score',
    score: 1,
    icon: 'emotional-health',
    iconBg: '#F56138',
    chartType: 'line',
    chartData: [70, 72, 75, 74, 76, 78, 79, 80, 81, 81],
    detailStats: [
      { label: 'Stress Level', value: '22', unit: '' },
      { label: 'Mood Score', value: '81', unit: '%' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [31, 33, 36, 38, 42, 40, 44, 46, 48],
      warning:  [10, 12, 15, 18, 22, 18, 16, 18, 14],
      critical: [4,  6,  8,  11, 15, 10, 8,  9,  6],
      optimalThreshold: 50,
      criticalThreshold: 75,
    },
    summary: SUMMARY,
    finalScore: 81,
    finalScoreSubtitle: 'Across 3 indicators',
    questionnaires: 7,
    questionnairesSubtitle: 'Good Reading',
    statusItems: [
      { title: 'Questionnaires', value: '7', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Biomarkers', value: '8/10', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Stress Index', value: '9', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
    ],
  },
  {
    id: 6,
    slug: 'hormones',
    title: 'Hormone Health',
    value: 49,
    label: 'Hormone health score',
    score: 1,
    icon: 'hormone-health',
    iconBg: '#E71590',
    chartType: 'line',
    chartData: [42, 44, 45, 43, 46, 47, 48, 47, 49, 49],
    detailStats: [
      { label: 'Cortisol', value: '18', unit: 'mcg/dL' },
      { label: 'Testosterone', value: '320', unit: 'ng/dL' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [30, 32, 35, 39, 43, 41, 45, 46, 48],
      warning:  [12, 15, 18, 22, 25, 21, 18, 20, 16],
      critical: [5,  8,  10, 14, 18, 12, 8,  10, 7],
      optimalThreshold: 50,
      criticalThreshold: 75,
    },
    summary: SUMMARY,
    finalScore: 49,
    finalScoreSubtitle: 'Across 2 indicators',
    questionnaires: 4,
    questionnairesSubtitle: 'Below Average',
    statusItems: [
      { title: 'Questionnaires', value: '3', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Cortisol', value: '4.2', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Biomarkers', value: '2', subtitle: 'Needs Immediate Attention', badge: 'Low', type: 'danger' },
    ],
  },
  {
    id: 7,
    slug: 'immune',
    title: 'Immune system',
    value: 62,
    label: 'Immune health score',
    score: 1,
    icon: 'immune-health',
    iconBg: '#00ADEF',
    chartType: 'line',
    chartData: [55, 57, 58, 56, 59, 60, 61, 60, 62, 62],
    detailStats: [
      { label: 'WBC Count', value: '6.2', unit: 'K/uL' },
      { label: 'CRP Level', value: '0.8', unit: 'mg/L' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [32, 34, 36, 39, 42, 41, 44, 46, 47],
      warning:  [11, 13, 16, 20, 24, 19, 17, 18, 15],
      critical: [4,  7,  9,  12, 16, 11, 8,  9,  6],
      optimalThreshold: 50,
      criticalThreshold: 76,
    },
    summary: SUMMARY,
    finalScore: 62,
    finalScoreSubtitle: 'Across 3 indicators',
    questionnaires: 5,
    questionnairesSubtitle: 'Average Reading',
    statusItems: [
      { title: 'Questionnaires', value: '5', subtitle: 'Average Reading', badge: 'In Range', type: 'success' },
      { title: 'Biomarkers', value: '3', subtitle: 'Needs Immediate Attention', badge: 'Low', type: 'danger' },
      { title: 'Immune Score', value: '7', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
    ],
  },
  {
    id: 8,
    slug: 'regenerative',
    title: 'Regenerative Medicine',
    value: 44,
    label: 'Regenerative score',
    score: 1,
    icon: 'regenerative-medicine',
    iconBg: '#FF3083',
    chartType: 'line',
    chartData: [38, 39, 40, 41, 40, 42, 43, 42, 44, 44],
    detailStats: [
      { label: 'Cell Renewal', value: '44', unit: '%' },
      { label: 'Inflammation', value: '1.2', unit: 'mg/L' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [29, 31, 34, 37, 41, 39, 43, 45, 47],
      warning:  [13, 15, 18, 22, 25, 20, 18, 20, 16],
      critical: [6,  8,  10, 14, 18, 12, 8,  10, 7],
      optimalThreshold: 51,
      criticalThreshold: 75,
    },
    summary: SUMMARY,
    finalScore: 44,
    finalScoreSubtitle: 'Across 2 indicators',
    questionnaires: 3,
    questionnairesSubtitle: 'Below Average',
    statusItems: [
      { title: 'Questionnaires', value: '3', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Inflammation', value: '4.2', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Biomarkers', value: '2', subtitle: 'Needs Immediate Attention', badge: 'Low', type: 'danger' },
    ],
  },
  {
    id: 9,
    slug: 'longevity',
    title: 'Long-term health outlook',
    value: 69,
    label: 'Longevity score',
    score: 1,
    icon: 'longevity',
    iconBg: '#7BC31B',
    chartType: 'line',
    chartData: [60, 62, 63, 64, 65, 66, 67, 68, 69, 69],
    detailStats: [
      { label: 'Longevity Score', value: '69', unit: '' },
      { label: 'Biological Age', value: '51', unit: 'yrs' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [30, 33, 35, 38, 42, 40, 44, 46, 48],
      warning:  [11, 14, 17, 21, 24, 19, 18, 19, 15],
      critical: [5,  7,  9,  13, 17, 11, 8,  9,  6],
      optimalThreshold: 50,
      criticalThreshold: 76,
    },
    summary: SUMMARY,
    finalScore: 69,
    finalScoreSubtitle: 'Across 3 indicators',
    questionnaires: 6,
    questionnairesSubtitle: 'Good Reading',
    statusItems: [
      { title: 'Questionnaires', value: '6', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Biomarkers', value: '8', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Longevity', value: '5', subtitle: 'Needs Attention', badge: 'Low', type: 'warning' },
    ],
  },
  {
    id: 10,
    slug: 'nutrition',
    title: 'Nutrition + Metabolic',
    value: 86,
    label: 'Nutrition score',
    score: 1,
    icon: 'nutrition',
    iconBg: '#A855F7',
    chartType: 'line',
    chartData: [78, 80, 82, 81, 83, 84, 85, 85, 86, 86],
    detailStats: [
      { label: 'Vitamin D', value: '42', unit: 'ng/mL' },
      { label: 'Glucose', value: '88', unit: 'mg/dL' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [31, 34, 36, 39, 43, 41, 45, 47, 49],
      warning:  [10, 12, 15, 18, 22, 18, 16, 18, 14],
      critical: [4,  6,  8,  11, 15, 10, 8,  9,  6],
      optimalThreshold: 52,
      criticalThreshold: 78,
    },
    summary: SUMMARY,
    finalScore: 86,
    finalScoreSubtitle: 'Across 3 indicators',
    questionnaires: 8,
    questionnairesSubtitle: 'Optimal Reading',
    statusItems: [
      { title: 'Questionnaires', value: '8', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Biomarkers', value: '9', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Glucose', value: '88', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
    ],
  },
  {
    id: 11,
    slug: 'detox',
    title: 'Detoxification',
    value: 32,
    label: 'Detox score',
    score: 1,
    icon: 'detoxification',
    iconBg: '#15803D',
    chartType: 'line',
    chartData: [28, 29, 30, 29, 31, 30, 31, 32, 31, 32],
    detailStats: [
      { label: 'Liver Enzymes', value: '42', unit: 'U/L' },
      { label: 'Heavy Metals', value: '1.2', unit: 'mcg/L' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [28, 31, 34, 37, 41, 39, 43, 45, 47],
      warning:  [14, 16, 18, 22, 25, 20, 18, 20, 16],
      critical: [8,  10, 11, 14, 18, 12, 9,  10, 8],
      optimalThreshold: 50,
      criticalThreshold: 75,
    },
    summary: SUMMARY,
    finalScore: 32,
    finalScoreSubtitle: 'Across 2 indicators',
    questionnaires: 3,
    questionnairesSubtitle: 'Needs Attention',
    statusItems: [
      { title: 'Questionnaires', value: '3', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Liver Enzymes', value: '42', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Heavy Metals', value: '1.2', subtitle: 'Needs Immediate Attention', badge: 'Low', type: 'danger' },
    ],
  },
  {
    id: 12,
    slug: 'gut',
    title: 'Gut Health',
    value: 96,
    label: 'Gut health score',
    score: 1,
    icon: 'gut-health',
    iconBg: '#7F1D1D',
    chartType: 'line',
    chartData: [82, 84, 86, 87, 88, 90, 91, 93, 95, 96],
    detailStats: [
      { label: 'Microbiome', value: '96', unit: '%' },
      { label: 'Inflammation', value: '0.4', unit: 'mg/L' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [33, 35, 37, 40, 44, 42, 46, 48, 50],
      warning:  [10, 12, 15, 18, 22, 18, 16, 18, 14],
      critical: [4,  6,  8,  11, 15, 10, 8,  9,  6],
      optimalThreshold: 52,
      criticalThreshold: 78,
    },
    summary: SUMMARY,
    finalScore: 96,
    finalScoreSubtitle: 'Across 3 indicators',
    questionnaires: 9,
    questionnairesSubtitle: 'Optimal Reading',
    statusItems: [
      { title: 'Questionnaires', value: '9', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Microbiome', value: '10', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Inflammation', value: '0.4', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
    ],
  },
];

export const HEALTH_AREAS = [
  { id: "nutrition", label: "Nutrition + Metabolic", value: 86, icon: "nutrition", color: "#A855F7" },
  { id: "hormone", label: "Hormone Health", value: 30, icon: "hormone-health", color: "#E71590" },
  { id: "movement", label: "Weekly activity balance", value: 78, icon: "movement", color: "#16A34A" },
  { id: "brain", label: "Mental clarity", value: 44, icon: "brain-health", color: "#DE2ED7" },
  { id: "recovery", label: "Recovery efficiency", value: 84, icon: "recovery", color: "#3F54E4" },
  { id: "cardio", label: "Cardiovascular efficiency", value: 88, icon: "heart-health", color: "#DC2626" },
  { id: "detoxification", label: "Detoxification", value: 32, icon: "detoxification", color: "#15803D" },
  { id: "immune", label: "Immune system", value: 48, icon: "immune-health", color: "#00ADEF" },
  { id: "stress", label: "Emotional Health + Stress", value: 74, icon: "emotional-health", color: "#F97316" },
  { id: "regen", label: "Regenerative Medicine", value: 70, icon: "regenerative-medicine", color: "#FF3083" },
  { id: "gut", label: "Gut Health", value: 96, icon: "gut-health", color: "#7F1D1D" },
  { id: "long-term", label: "Long-term health outlook", value: 92, icon: "longevity", color: "#7BC31B" },
  { id: "sleep", label: "Sleep quality", value: 66, icon: "recovery", color: "#8B5CF6" },
  { id: "hydration", label: "Hydration balance", value: 58, icon: "nutrition", color: "#06B6D4" },
  { id: "metabolic-flex", label: "Metabolic flexibility", value: 81, icon: "movement", color: "#84CC16" },
];
