import { SCORING_SECTIONS_BY_SLUG } from '@/app/lib/scoringSectionsBySlug';
import { BIOMARKER_WEARABLE_SECTIONS_BY_SLUG } from '@/app/lib/biomarkerWearableSectionsBySlug';

export const MONTHS = ['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov'];

const SUMMARY = 'Your health score is currently showing some areas of concern. At this time, some of the tracked indicators are performing below optimal levels, and several biomarkers fall outside the recommended range. This suggests potential inconsistencies in your current health factors.';

const HR_CLINICIAN_LINE =
  'Work with your clinician to interpret these results in the context of your full history and goals.';
const HR_RETEST_LINE =
  'Retesting on the schedule your care team recommends helps confirm trends and adjust your plan.';

/** Card body (shown twice in the card) + modal lines for `/biomarkers/[slug]` Health Recommendation. */
function healthRecommendationFromBody(cardBody, modalSubtitle) {
  return {
    paragraphs: [cardBody, cardBody],
    modalSubtitle,
    modalContent: [cardBody, HR_CLINICIAN_LINE, HR_RETEST_LINE],
  };
}

const METRICS_DATA = [
  {
    id: 1,
    slug: 'movement',
    title: 'Physical Fitness',
    value: 85,
    label: 'Weekly activity score',
    score: 1,
    icon: 'movement',
    iconBg: '#09BC4E',
    chartType: 'line',
    chartData: [60, 62, 61, 65, 70, 72, 75, 78, 80, 85],
    detailStats: [
      { label: 'Active Minutes', value: '62', unit: 'min' },
      { label: 'Step Count', value: '8,543', unit: '' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [32, 34, 36, 39, 43, 41, 45, 47, 49],
      warning:  [11, 14, 17, 21, 24, 19, 18, 19, 15],
      critical: [4,  7,  9,  13, 17, 11, 8,  9,  6],
      optimalThreshold: 52,
      criticalThreshold: 78,
    },
    summary: SUMMARY,
    finalScore: 85,
    finalScoreSubtitle: 'Across 3 indicators',
    questionnaires: 6,
    questionnairesSubtitle: 'Optimal Reading',
    statusItems: [
      { title: 'Questionnaires', value: '6', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Biomarkers', value: '8', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Activity Score', value: '3', subtitle: 'Needs Attention', badge: 'Low', type: 'warning' },
    ],
    healthRecommendation: healthRecommendationFromBody(
      'Your Physical Fitness score highlights how well your daily movement, training, and recovery are supporting your health. When tracked indicators fall short of optimal levels, it may reflect inconsistent activity, recovery debt, or load management worth reviewing with your care team.',
      'Physical Fitness: next steps',
    ),
  },
  {
    id: 2,
    slug: 'heart',
    title: 'CV (Heart) Health',
    value: 76,
    label: 'Heart health score',
    score: 1,
    icon: 'heart-health',
    iconBg: '#E51C29',
    chartType: 'line',
    chartData: [70, 68, 72, 71, 74, 73, 75, 76, 74, 76],
    detailStats: [
      { label: 'Resting HR', value: '62', unit: 'bpm' },
      { label: 'Variability', value: '35', unit: 'ms' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [31, 33, 35, 38, 42, 40, 44, 45, 47],
      warning:  [12, 15, 18, 22, 25, 21, 18, 20, 16],
      critical: [5,  8,  10, 13, 17, 12, 8,  10, 7],
      optimalThreshold: 50,
      criticalThreshold: 76,
    },
    summary: SUMMARY,
    finalScore: 76,
    finalScoreSubtitle: 'Across 2 indicators',
    questionnaires: 8,
    questionnairesSubtitle: 'Optimal Reading',
    statusItems: [
      { title: 'Questionnaires', value: '3', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Biomarkers', value: '4.2', subtitle: 'Needs Immediate Attention', badge: 'Low', type: 'danger' },
      { title: 'Biomarkers', value: '8', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
    ],
    healthRecommendation: healthRecommendationFromBody(
      'Your CV (Heart) Health score reflects how cardiovascular strain, rhythm, and recovery are trending. If several markers sit outside the ideal range, it may point to stress on the heart and vessels that should be reviewed alongside your clinician.',
      'CV (Heart) Health: clinical context',
    ),
  },
  {
    id: 3,
    slug: 'sleep',
    title: 'Sleep and Recovery',
    value: 46,
    label: 'Recovery score',
    score: 1,
    icon: 'recovery',
    iconBg: '#3F54E4',
    chartType: 'line',
    chartData: [40, 42, 44, 41, 43, 45, 44, 46, 45, 46],
    detailStats: [
      { label: 'Sleep Quality', value: '72', unit: '%' },
      { label: 'HRV', value: '28', unit: 'ms' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [30, 32, 35, 38, 42, 40, 44, 46, 48],
      warning:  [12, 15, 18, 22, 25, 20, 18, 20, 16],
      critical: [5,  8,  10, 14, 18, 12, 8,  10, 6],
      optimalThreshold: 50,
      criticalThreshold: 75,
    },
    summary: SUMMARY,
    finalScore: 46,
    finalScoreSubtitle: 'Across 2 indicators',
    questionnaires: 4,
    questionnairesSubtitle: 'Below Average',
    statusItems: [
      { title: 'Questionnaires', value: '3', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Sleep Score', value: '4.2', subtitle: 'Needs Immediate Attention', badge: 'Low', type: 'danger' },
      { title: 'HRV', value: '2.8', subtitle: 'Needs Immediate Attention', badge: 'Low', type: 'danger' },
    ],
    healthRecommendation: healthRecommendationFromBody(
      'Your Sleep and Recovery score reflects how restful sleep and autonomic balance are supporting repair and stress regulation. When recovery metrics underperform, it often links to irregular sleep, stress load, or training timing—priorities to address with your team.',
      'Sleep and Recovery: priorities',
    ),
  },
  {
    id: 4,
    slug: 'brain',
    title: 'Brain Health',
    value: 56,
    label: 'Brain health score',
    score: 1,
    icon: 'brain-health',
    iconBg: '#DE2ED7',
    chartType: 'bar',
    chartData: [30, 45, 50, 40, 55, 35, 56, 42, 38, 50],
    detailStats: [
      { label: 'Focus Score', value: '56', unit: '%' },
      { label: 'Stress Index', value: '42', unit: '' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [29, 32, 34, 37, 41, 39, 43, 45, 46],
      warning:  [12, 14, 17, 20, 24, 19, 17, 18, 15],
      critical: [6,  8,  10, 12, 16, 11, 9,  10, 7],
      optimalThreshold: 51,
      criticalThreshold: 77,
    },
    summary: SUMMARY,
    finalScore: 56,
    finalScoreSubtitle: 'Across 2 indicators',
    questionnaires: 5,
    questionnairesSubtitle: 'Average Reading',
    statusItems: [
      { title: 'Questionnaires', value: '5', subtitle: 'Average Reading', badge: 'In Range', type: 'success' },
      { title: 'Stress Level', value: '7', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Focus', value: '3', subtitle: 'Needs Immediate Attention', badge: 'Low', type: 'danger' },
    ],
    healthRecommendation: healthRecommendationFromBody(
      'Your Brain Health score captures how focus, stress load, and cognitive resilience are tracking. Several indicators outside the optimal band may suggest attention to sleep, stress, and mental load that your clinician can help interpret.',
      'Brain Health: focus areas',
    ),
  },
  {
    id: 5,
    slug: 'emotional',
    title: 'Emotional Health + Stress',
    value: 81,
    label: 'Emotional health score',
    score: 1,
    icon: 'emotional-health',
    iconBg: '#F56138',
    chartType: 'line',
    chartData: [70, 72, 75, 74, 76, 78, 79, 80, 81, 81],
    detailStats: [
      { label: 'Stress Level', value: '22', unit: '' },
      { label: 'Mood Score', value: '81', unit: '%' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [31, 33, 36, 38, 42, 40, 44, 46, 48],
      warning:  [10, 12, 15, 18, 22, 18, 16, 18, 14],
      critical: [4,  6,  8,  11, 15, 10, 8,  9,  6],
      optimalThreshold: 50,
      criticalThreshold: 75,
    },
    summary: SUMMARY,
    finalScore: 81,
    finalScoreSubtitle: 'Across 3 indicators',
    questionnaires: 7,
    questionnairesSubtitle: 'Good Reading',
    statusItems: [
      { title: 'Questionnaires', value: '7', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Biomarkers', value: '8/10', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Stress Index', value: '9', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
    ],
    healthRecommendation: healthRecommendationFromBody(
      'Your Emotional Health + Stress score reflects how stress physiology and mood-related signals are tracking. When readings are below optimal, it may indicate elevated strain or recovery gaps worth exploring in your care plan.',
      'Emotional Health + Stress: support',
    ),
  },
  {
    id: 6,
    slug: 'hormones',
    title: 'Hormone Health',
    value: 49,
    label: 'Hormone health score',
    score: 1,
    icon: 'hormone-health',
    iconBg: '#E71590',
    chartType: 'line',
    chartData: [42, 44, 45, 43, 46, 47, 48, 47, 49, 49],
    detailStats: [
      { label: 'Cortisol', value: '18', unit: 'mcg/dL' },
      { label: 'Testosterone', value: '320', unit: 'ng/dL' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [30, 32, 35, 39, 43, 41, 45, 46, 48],
      warning:  [12, 15, 18, 22, 25, 21, 18, 20, 16],
      critical: [5,  8,  10, 14, 18, 12, 8,  10, 7],
      optimalThreshold: 50,
      criticalThreshold: 75,
    },
    summary: SUMMARY,
    finalScore: 49,
    finalScoreSubtitle: 'Across 2 indicators',
    questionnaires: 4,
    questionnairesSubtitle: 'Below Average',
    statusItems: [
      { title: 'Questionnaires', value: '3', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Cortisol', value: '4.2', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Biomarkers', value: '2', subtitle: 'Needs Immediate Attention', badge: 'Low', type: 'danger' },
    ],
    healthRecommendation: healthRecommendationFromBody(
      'Your Hormone Health score reflects how endocrine balance may be influencing energy, stress, and metabolism. Several biomarkers outside the recommended range can signal patterns that deserve individualized interpretation with your clinician.',
      'Hormone Health: interpretation',
    ),
  },
  {
    id: 7,
    slug: 'immune',
    title: 'Immune system',
    value: 62,
    label: 'Immune health score',
    score: 1,
    icon: 'immune-health',
    iconBg: '#00ADEF',
    chartType: 'line',
    chartData: [55, 57, 58, 56, 59, 60, 61, 60, 62, 62],
    detailStats: [
      { label: 'WBC Count', value: '6.2', unit: 'K/uL' },
      { label: 'CRP Level', value: '0.8', unit: 'mg/L' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [32, 34, 36, 39, 42, 41, 44, 46, 47],
      warning:  [11, 13, 16, 20, 24, 19, 17, 18, 15],
      critical: [4,  7,  9,  12, 16, 11, 8,  9,  6],
      optimalThreshold: 50,
      criticalThreshold: 76,
    },
    summary: SUMMARY,
    finalScore: 62,
    finalScoreSubtitle: 'Across 3 indicators',
    questionnaires: 5,
    questionnairesSubtitle: 'Average Reading',
    statusItems: [
      { title: 'Questionnaires', value: '5', subtitle: 'Average Reading', badge: 'In Range', type: 'success' },
      { title: 'Biomarkers', value: '3', subtitle: 'Needs Immediate Attention', badge: 'Low', type: 'danger' },
      { title: 'Immune Score', value: '7', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
    ],
    healthRecommendation: healthRecommendationFromBody(
      'Your Immune Health score reflects how inflammatory and immune-related markers are tracking. When multiple indicators are suboptimal, it may suggest immune stress, recovery needs, or follow-up testing to clarify the pattern.',
      'Immune Health: follow-up',
    ),
  },
  {
    id: 8,
    slug: 'regenerative',
    title: 'Cancer Prevention',
    value: 44,
    label: 'Prevention score',
    score: 1,
    icon: 'regenerative-medicine',
    iconBg: '#FF3083',
    chartType: 'line',
    chartData: [38, 39, 40, 41, 40, 42, 43, 42, 44, 44],
    detailStats: [
      { label: 'Cell Renewal', value: '44', unit: '%' },
      { label: 'Inflammation', value: '1.2', unit: 'mg/L' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [29, 31, 34, 37, 41, 39, 43, 45, 47],
      warning:  [13, 15, 18, 22, 25, 20, 18, 20, 16],
      critical: [6,  8,  10, 14, 18, 12, 8,  10, 7],
      optimalThreshold: 51,
      criticalThreshold: 75,
    },
    summary: SUMMARY,
    finalScore: 44,
    finalScoreSubtitle: 'Across 2 indicators',
    questionnaires: 3,
    questionnairesSubtitle: 'Below Average',
    statusItems: [
      { title: 'Questionnaires', value: '3', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Inflammation', value: '4.2', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Biomarkers', value: '2', subtitle: 'Needs Immediate Attention', badge: 'Low', type: 'danger' },
    ],
    healthRecommendation: healthRecommendationFromBody(
      'Your Cancer Prevention score summarizes protective and regenerative signals from your labs. When tracked indicators are not optimal, it highlights opportunities for screening focus, inflammation control, and lifestyle alignment with your clinician.',
      'Cancer Prevention: protective focus',
    ),
  },
  {
    id: 9,
    slug: 'longevity',
    title: 'Longevity',
    value: 69,
    label: 'Longevity score',
    score: 1,
    icon: 'longevity',
    iconBg: '#7BC31B',
    chartType: 'line',
    chartData: [60, 62, 63, 64, 65, 66, 67, 68, 69, 69],
    detailStats: [
      { label: 'Longevity Score', value: '69', unit: '' },
      { label: 'Biological Age', value: '51', unit: 'yrs' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [30, 33, 35, 38, 42, 40, 44, 46, 48],
      warning:  [11, 14, 17, 21, 24, 19, 18, 19, 15],
      critical: [5,  7,  9,  13, 17, 11, 8,  9,  6],
      optimalThreshold: 50,
      criticalThreshold: 76,
    },
    summary: SUMMARY,
    finalScore: 69,
    finalScoreSubtitle: 'Across 3 indicators',
    questionnaires: 6,
    questionnairesSubtitle: 'Good Reading',
    statusItems: [
      { title: 'Questionnaires', value: '6', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Biomarkers', value: '8', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Longevity', value: '5', subtitle: 'Needs Attention', badge: 'Low', type: 'warning' },
    ],
    healthRecommendation: healthRecommendationFromBody(
      'Your Longevity score reflects how key aging and vitality markers are trending over time. Several biomarkers outside the ideal range may point to areas—metabolic health, inflammation, and recovery—worth prioritizing in your plan.',
      'Longevity: long-term focus',
    ),
  },
  {
    id: 10,
    slug: 'nutrition',
    title: 'Nutrition',
    value: 86,
    label: 'Nutrition score',
    score: 1,
    icon: 'nutrition',
    iconBg: '#A855F7',
    chartType: 'line',
    chartData: [78, 80, 82, 81, 83, 84, 85, 85, 86, 86],
    detailStats: [
      { label: 'Vitamin D', value: '42', unit: 'ng/mL' },
      { label: 'Glucose', value: '88', unit: 'mg/dL' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [31, 34, 36, 39, 43, 41, 45, 47, 49],
      warning:  [10, 12, 15, 18, 22, 18, 16, 18, 14],
      critical: [4,  6,  8,  11, 15, 10, 8,  9,  6],
      optimalThreshold: 52,
      criticalThreshold: 78,
    },
    summary: SUMMARY,
    finalScore: 86,
    finalScoreSubtitle: 'Across 3 indicators',
    questionnaires: 8,
    questionnairesSubtitle: 'Optimal Reading',
    statusItems: [
      { title: 'Questionnaires', value: '8', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Biomarkers', value: '9', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Glucose', value: '88', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
    ],
    healthRecommendation: {
      paragraphs: [
        'Your Nutrition & Metabolic Health score is currently low, indicating that your body may be under strain in maintaining stable metabolic function. At this time, none of the tracked indicators are performing at an optimal level, and several biomarkers fall outside the recommended range. This suggests potential inconsistencies in factors such as nutrition, blood sugar regulation, or energy balance.',
        'Your Nutrition & Metabolic Health score is currently low, indicating that your body may be under strain in maintaining stable metabolic function. At this time, none of the tracked indicators are performing at an optimal level, and several biomarkers fall outside the recommended range. This suggests potential inconsistencies in factors such as nutrition, blood sugar regulation, or energy balance.',
      ],
      modalSubtitle: 'Nutrition & Metabolic Health: areas to address',
      modalContent: [
        'Your Nutrition & Metabolic Health score is currently low, indicating that your body may be under strain in maintaining stable metabolic function. At this time, none of the tracked indicators are performing at an optimal level, and several biomarkers fall outside the recommended range. This suggests potential inconsistencies in factors such as nutrition, blood sugar regulation, or energy balance.',
        'Work with your clinician to interpret these results in the context of your full history and goals.',
        'Retesting on the schedule your care team recommends helps confirm trends and adjust your plan.',
      ],
    },
  },
  {
    id: 11,
    slug: 'detox',
    title: 'Detoxification',
    value: 32,
    label: 'Detox score',
    score: 1,
    icon: 'detoxification',
    iconBg: '#15803D',
    chartType: 'line',
    chartData: [28, 29, 30, 29, 31, 30, 31, 32, 31, 32],
    detailStats: [
      { label: 'Liver Enzymes', value: '42', unit: 'U/L' },
      { label: 'Heavy Metals', value: '1.2', unit: 'mcg/L' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [28, 31, 34, 37, 41, 39, 43, 45, 47],
      warning:  [14, 16, 18, 22, 25, 20, 18, 20, 16],
      critical: [8,  10, 11, 14, 18, 12, 9,  10, 8],
      optimalThreshold: 50,
      criticalThreshold: 75,
    },
    summary: SUMMARY,
    finalScore: 32,
    finalScoreSubtitle: 'Across 2 indicators',
    questionnaires: 3,
    questionnairesSubtitle: 'Needs Attention',
    statusItems: [
      { title: 'Questionnaires', value: '3', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Liver Enzymes', value: '42', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Heavy Metals', value: '1.2', subtitle: 'Needs Immediate Attention', badge: 'Low', type: 'danger' },
    ],
    healthRecommendation: healthRecommendationFromBody(
      'Your Detoxification score reflects how liver handling and exposure-related burden may be influencing wellness. Out-of-range markers may warrant discussion of environment, diet, and organ function with your care team.',
      'Detoxification: clearance and exposure',
    ),
  },
  {
    id: 12,
    slug: 'gut',
    title: 'Gut Health',
    value: 96,
    label: 'Gut health score',
    score: 1,
    icon: 'gut-health',
    iconBg: '#7F1D1D',
    chartType: 'line',
    chartData: [82, 84, 86, 87, 88, 90, 91, 93, 95, 96],
    detailStats: [
      { label: 'Microbiome', value: '96', unit: '%' },
      { label: 'Inflammation', value: '0.4', unit: 'mg/L' },
    ],
    detailChart: {
      months: MONTHS,
      optimal:  [33, 35, 37, 40, 44, 42, 46, 48, 50],
      warning:  [10, 12, 15, 18, 22, 18, 16, 18, 14],
      critical: [4,  6,  8,  11, 15, 10, 8,  9,  6],
      optimalThreshold: 52,
      criticalThreshold: 78,
    },
    summary: SUMMARY,
    finalScore: 96,
    finalScoreSubtitle: 'Across 3 indicators',
    questionnaires: 9,
    questionnairesSubtitle: 'Optimal Reading',
    statusItems: [
      { title: 'Questionnaires', value: '9', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Microbiome', value: '10', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Inflammation', value: '0.4', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
    ],
    healthRecommendation: healthRecommendationFromBody(
      'Your Gut Health score reflects how digestion, barrier function, and inflammation signals are tracking. When indicators are not in the optimal band, it may suggest microbiome or digestive patterns to explore with your clinician.',
      'Gut Health: digestive balance',
    ),
  },
  {
    id: 13,
    slug: 'metabolic',
    title: 'Metabolic Health',
    value: 78,
    label: 'Metabolic score',
    score: 1,
    icon: 'metabolic',
    iconBg: '#EA580C',
    chartType: 'line',
    chartData: [68, 70, 72, 71, 74, 75, 76, 77, 78, 78],
    detailStats: [
      { label: 'HbA1c', value: '5.2', unit: '%' },
      { label: 'Fasting Glucose', value: '88', unit: 'mg/dL' },
    ],
    detailChart: {
      months: MONTHS,
      optimal: [31, 34, 36, 39, 43, 41, 45, 47, 49],
      warning: [10, 12, 15, 18, 22, 18, 16, 18, 14],
      critical: [4, 6, 8, 11, 15, 10, 8, 9, 6],
      optimalThreshold: 52,
      criticalThreshold: 78,
    },
    summary: SUMMARY,
    finalScore: 78,
    finalScoreSubtitle: 'Across 3 indicators',
    questionnaires: 6,
    questionnairesSubtitle: 'Good Reading',
    statusItems: [
      { title: 'Questionnaires', value: '6', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Biomarkers', value: '7', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Glucose', value: '88', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
    ],
    healthRecommendation: healthRecommendationFromBody(
      'Your Metabolic Health score reflects how blood sugar control, lipids, and energy regulation are tracking. Several markers outside the recommended range may indicate metabolic strain worth addressing through nutrition, activity, and medical follow-up.',
      'Metabolic Health: regulation',
    ),
  },
  {
    id: 14,
    slug: 'toxin-exposure',
    title: 'Toxin Exposure',
    value: 54,
    label: 'Exposure score',
    score: 1,
    icon: 'toxin-exposure',
    iconBg: '#0D9488',
    chartType: 'line',
    chartData: [48, 50, 51, 52, 53, 52, 53, 54, 54, 54],
    detailStats: [
      { label: 'Heavy Metals', value: '1.1', unit: 'mcg/L' },
      { label: 'Pesticides', value: 'Low', unit: '' },
    ],
    detailChart: {
      months: MONTHS,
      optimal: [28, 31, 34, 37, 41, 39, 43, 45, 47],
      warning: [14, 16, 18, 22, 25, 20, 18, 20, 16],
      critical: [8, 10, 11, 14, 18, 12, 9, 10, 8],
      optimalThreshold: 50,
      criticalThreshold: 75,
    },
    summary: SUMMARY,
    finalScore: 54,
    finalScoreSubtitle: 'Across 2 indicators',
    questionnaires: 4,
    questionnairesSubtitle: 'Average Reading',
    statusItems: [
      { title: 'Questionnaires', value: '4', subtitle: 'Average Reading', badge: 'In Range', type: 'success' },
      { title: 'Biomarkers', value: '3', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'Exposure Index', value: '5', subtitle: 'Average Reading', badge: 'In Range', type: 'success' },
    ],
    healthRecommendation: healthRecommendationFromBody(
      'Your Toxin Exposure score summarizes environmental and clearance-related signals. When indicators are suboptimal, it may reflect exposure burden or clearance limits that your care team can help contextualize and reduce over time.',
      'Toxin Exposure: burden and clearance',
    ),
  },
  {
    id: 15,
    slug: 'liver-kidney',
    title: 'Liver and Kidney Health',
    value: 71,
    label: 'Organ health score',
    score: 1,
    icon: 'liver-kidney',
    iconBg: '#7C3AED',
    chartType: 'line',
    chartData: [62, 64, 65, 66, 67, 68, 69, 70, 71, 71],
    detailStats: [
      { label: 'ALT', value: '28', unit: 'U/L' },
      { label: 'eGFR', value: '88', unit: 'mL/min' },
    ],
    detailChart: {
      months: MONTHS,
      optimal: [32, 34, 36, 39, 42, 41, 44, 46, 48],
      warning: [11, 13, 16, 20, 24, 19, 17, 18, 15],
      critical: [4, 7, 9, 12, 16, 11, 8, 9, 6],
      optimalThreshold: 50,
      criticalThreshold: 76,
    },
    summary: SUMMARY,
    finalScore: 71,
    finalScoreSubtitle: 'Across 3 indicators',
    questionnaires: 5,
    questionnairesSubtitle: 'Good Reading',
    statusItems: [
      { title: 'Questionnaires', value: '5', subtitle: 'Good Reading', badge: 'In Range', type: 'success' },
      { title: 'Liver Enzymes', value: '28', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
      { title: 'Kidney Function', value: '88', subtitle: 'Optimal Reading', badge: 'In Range', type: 'success' },
    ],
    healthRecommendation: healthRecommendationFromBody(
      'Your Liver and Kidney Health score reflects how filtration, enzymes, and clearance are performing. Several biomarkers outside the optimal range may signal organ stress, hydration, or medication factors to review with your clinician.',
      'Liver and Kidney Health: organ function',
    ),
  },
  {
    id: 16,
    slug: 'inflammation',
    title: 'Inflammation',
    value: 58,
    label: 'Inflammation score',
    score: 1,
    icon: 'inflammation',
    iconBg: '#DC2626',
    chartType: 'line',
    chartData: [52, 53, 54, 55, 56, 56, 57, 57, 58, 58],
    detailStats: [
      { label: 'hs-CRP', value: '1.2', unit: 'mg/L' },
      { label: 'ESR', value: '8', unit: 'mm/hr' },
    ],
    detailChart: {
      months: MONTHS,
      optimal: [30, 32, 35, 38, 42, 40, 44, 46, 48],
      warning: [12, 15, 18, 22, 25, 20, 18, 20, 16],
      critical: [5, 8, 10, 14, 18, 12, 8, 10, 6],
      optimalThreshold: 50,
      criticalThreshold: 75,
    },
    summary: SUMMARY,
    finalScore: 58,
    finalScoreSubtitle: 'Across 2 indicators',
    questionnaires: 4,
    questionnairesSubtitle: 'Average Reading',
    statusItems: [
      { title: 'Questionnaires', value: '4', subtitle: 'Average Reading', badge: 'In Range', type: 'success' },
      { title: 'Biomarkers', value: '5', subtitle: 'Needs Attention', badge: 'Out of Range', type: 'warning' },
      { title: 'CRP', value: '1.2', subtitle: 'Average Reading', badge: 'In Range', type: 'success' },
    ],
    healthRecommendation: healthRecommendationFromBody(
      'Your Inflammation score reflects systemic inflammatory signals from your labs. When multiple markers are elevated or suboptimal, it may point to stress, recovery, or underlying drivers that merit coordinated follow-up.',
      'Inflammation: systemic signals',
    ),
  },
];

export const METRICS = METRICS_DATA.map((m) => ({
  ...m,
  scoringSection: SCORING_SECTIONS_BY_SLUG[m.slug],
  biomarkerWearableSection: BIOMARKER_WEARABLE_SECTIONS_BY_SLUG[m.slug],
}));

export const HEALTH_AREAS = [
  { id: 'nutrition', label: 'Nutrition', value: 71, icon: 'nutrition', color: '#F97316' },
  { id: 'metabolic', label: 'Metabolic Health', value: 70, icon: 'metabolic', color: '#F59E0B' },
  { id: 'sleep-recovery', label: 'Sleep + Recovery', value: 74, icon: 'recovery', color: '#EAB308' },
  { id: 'movement', label: 'Physical Fitness', value: 65, icon: 'movement', color: '#84CC16' },
  { id: 'emotional', label: 'Emotional Health', value: 38, icon: 'emotional-health', color: '#22C55E' },
  { id: 'toxin-exposure', label: 'Toxin Exposure', value: 42, icon: 'toxin-exposure', color: '#38BDF8' },
  { id: 'liver-kidney', label: 'Liver + Kidney Health', value: 60, icon: 'liver-kidney', color: '#3B82F6' },
  { id: 'hormone', label: 'Hormone Health', value: 71, icon: 'hormone-health', color: '#1E40AF' },
  { id: 'gut', label: 'Gut Health', value: 88, icon: 'gut-health', color: '#9333EA' },
  { id: 'inflammation', label: 'Inflammation', value: 55, icon: 'inflammation', color: '#D946EF' },
  { id: 'immune', label: 'Immune Health', value: 69, icon: 'immune-health', color: '#EC4899' },
  { id: 'heart', label: 'CV (Heart) Health', value: 90, icon: 'heart-health', color: '#F43F5E' },
  { id: 'cancer', label: 'Cancer Prevention', value: 62, icon: 'regenerative-medicine', color: '#EF4444' },
  { id: 'brain', label: 'Brain Health', value: 77, icon: 'brain-health', color: '#FB923C' },
  { id: 'longevity', label: 'Longevity', value: 73, icon: 'longevity', color: '#EA580C' },
];
